title: <p align="center"> Hemanth S S </p>
logo: /assets/img/logo.png
description: 
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/hemanth-ss-936267130/">LinkedIn</a> |      
  <a href="https://github.com/sschintha">GitHub</a>
  
  
theme: jekyll-theme-minimal  
  

